
// This file has been generated by the GUI designer. Do not modify.
public partial class MainWindow
{
	private global::Gtk.Fixed fixed1;
	private global::Gtk.DrawingArea drawingarea1;
	private global::Gtk.Entry entry1;
	private global::Gtk.Button button1;
	private global::Gtk.SpinButton spinbutton1;
	private global::Gtk.SpinButton spinbutton2;
	private global::Gtk.Label label1;
	private global::Gtk.Label label2;
	private global::Gtk.SpinButton spinbutton3;
	private global::Gtk.SpinButton spinbutton4;
	private global::Gtk.Button button2;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.WidthRequest = 600;
		this.HeightRequest = 600;
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed ();
		this.fixed1.WidthRequest = 600;
		this.fixed1.HeightRequest = 600;
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.drawingarea1 = new global::Gtk.DrawingArea ();
		this.drawingarea1.WidthRequest = 600;
		this.drawingarea1.HeightRequest = 220;
		this.drawingarea1.Name = "drawingarea1";
		this.fixed1.Add (this.drawingarea1);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.drawingarea1]));
		w1.Y = 50;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.entry1 = new global::Gtk.Entry ();
		this.entry1.CanFocus = true;
		this.entry1.Name = "entry1";
		this.entry1.Text = global::Mono.Unix.Catalog.GetString ("/home/jirvoz/Stažené/meteodata.csv");
		this.entry1.IsEditable = true;
		this.entry1.InvisibleChar = '•';
		this.fixed1.Add (this.entry1);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.entry1]));
		w2.X = 6;
		w2.Y = 12;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button1 = new global::Gtk.Button ();
		this.button1.CanFocus = true;
		this.button1.Name = "button1";
		this.button1.UseUnderline = true;
		this.button1.Label = global::Mono.Unix.Catalog.GetString ("Načíst");
		this.fixed1.Add (this.button1);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.button1]));
		w3.X = 173;
		w3.Y = 11;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.spinbutton1 = new global::Gtk.SpinButton (1, 52, 1);
		this.spinbutton1.CanFocus = true;
		this.spinbutton1.Name = "spinbutton1";
		this.spinbutton1.Adjustment.PageIncrement = 10;
		this.spinbutton1.ClimbRate = 1;
		this.spinbutton1.Numeric = true;
		this.spinbutton1.Value = 1;
		this.fixed1.Add (this.spinbutton1);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.spinbutton1]));
		w4.X = 286;
		w4.Y = 12;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.spinbutton2 = new global::Gtk.SpinButton (1, 52, 1);
		this.spinbutton2.CanFocus = true;
		this.spinbutton2.Name = "spinbutton2";
		this.spinbutton2.Adjustment.PageIncrement = 10;
		this.spinbutton2.ClimbRate = 1;
		this.spinbutton2.Numeric = true;
		this.spinbutton2.Value = 1;
		this.fixed1.Add (this.spinbutton2);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.spinbutton2]));
		w5.X = 354;
		w5.Y = 11;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label1 = new global::Gtk.Label ();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Týden:");
		this.fixed1.Add (this.label1);
		global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label1]));
		w6.X = 240;
		w6.Y = 15;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label2 = new global::Gtk.Label ();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Rok:");
		this.fixed1.Add (this.label2);
		global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label2]));
		w7.X = 418;
		w7.Y = 15;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.spinbutton3 = new global::Gtk.SpinButton (1975, 2015, 1);
		this.spinbutton3.CanFocus = true;
		this.spinbutton3.Name = "spinbutton3";
		this.spinbutton3.Adjustment.PageIncrement = 10;
		this.spinbutton3.ClimbRate = 1;
		this.spinbutton3.Numeric = true;
		this.spinbutton3.Value = 1975;
		this.fixed1.Add (this.spinbutton3);
		global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.spinbutton3]));
		w8.X = 457;
		w8.Y = 12;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.spinbutton4 = new global::Gtk.SpinButton (1975, 2015, 1);
		this.spinbutton4.CanFocus = true;
		this.spinbutton4.Name = "spinbutton4";
		this.spinbutton4.Adjustment.PageIncrement = 10;
		this.spinbutton4.ClimbRate = 1;
		this.spinbutton4.Numeric = true;
		this.spinbutton4.Value = 1976;
		this.fixed1.Add (this.spinbutton4);
		global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.spinbutton4]));
		w9.X = 523;
		w9.Y = 12;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button2 = new global::Gtk.Button ();
		this.button2.CanFocus = true;
		this.button2.Name = "button2";
		this.button2.UseUnderline = true;
		this.button2.Label = global::Mono.Unix.Catalog.GetString ("Zobrazit");
		this.fixed1.Add (this.button2);
		global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.button2]));
		w10.X = 596;
		w10.Y = 11;
		this.Add (this.fixed1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 800;
		this.DefaultHeight = 600;
		this.button2.Hide ();
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.drawingarea1.ExposeEvent += new global::Gtk.ExposeEventHandler (this.OnDrawingarea1ExposeEvent);
		this.button1.Clicked += new global::System.EventHandler (this.OnButton1Clicked);
		this.button2.Clicked += new global::System.EventHandler (this.OnButton2Clicked);
	}
}
